version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: okproje_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      DB_HOST: ${DB_HOST:-mysql}
      REDIS_HOST: ${REDIS_HOST:-redis}
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.25-alpine
    container_name: okproje_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: okproje_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-okproje}
      MYSQL_USER: ${DB_USERNAME:-okproje}
      MYSQL_PASSWORD: ${DB_PASSWORD:-change_me}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: okproje_redis
    ports:
      - "6379:6379"

  node:
    image: node:20-alpine
    container_name: okproje_node
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - app

volumes:
  db_data:


