services:

  livekit:
    image: livekit/livekit-server:latest
    container_name: okproje_livekit
    command: >
      --dev --bind 0.0.0.0
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY:-devkey}: ${LIVEKIT_API_SECRET:-devsecret}"
    ports:
      - "7880:7880"
    restart: unless-stopped

  turn:
    image: coturn/coturn
    container_name: okproje_turn
    command: >
      -n --log-file=stdout
      --min-port=49160 --max-port=49200
      --realm=okproje.local
      --lt-cred-mech
      --user=${TURN_USERNAME:-turnuser}:${TURN_PASSWORD:-turnpass}
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "49160-49200:49160-49200/udp"
    restart: unless-stopped

volumes:
  db_data:


